2025-03-18 05:27:03,794 - k8sgpt_service - INFO - Redis cache connection established
2025-03-18 05:27:03,869 - k8sgpt_service - ERROR - Failed to connect to RabbitMQ: ConnectionClosedByBroker: (530) 'NOT_ALLOWED - vhost  not found'
